### ISSUE TITLE
Circle markup needs to call markup.save()

### ISSUE THREAD

**Issue by tkoft** [Q726kbXuN/nytxw_puz#16]
https://github.com/Q726kbXuN/nytxw_puz/blob/master/nyt.py#L308

Puzzles with circle markups don't get output properly, `markup.save()` needs to get called to save the markups to the puz extension. E.g. The 2020-10-12 puzzle

**Comment by Q726kbXuN** [comment]
@tkoft 

Can you provide more details?  Right now if I convert 2020-10-12 and open the resulting puzzle in Across Lite, I see:

![image](https://user-images.githubusercontent.com/79105979/137006231-57a71bf6-b94c-497e-a1ee-6bdca6e75a3f.png)

This is because `save` is called during the [tobytes](https://github.com/Q726kbXuN/nytxw_puz/blob/master/puz.py#L239) operation.

This did reveal an unrelated bug with the notes not handling a None case that I'll be fixing.

**Comment by Q726kbXuN** [comment]
5fb7e592072695bb0e6cc60b3d490a30ba5f5186 fixes the issue with the notes.
