### ISSUE TITLE
Windows Defender Virus Threat

### ISSUE THREAD

**Issue by hankscorpio83** [Q726kbXuN/nytxw_puz#8]
I assume it's a false positive, but just a heads up that the default Windows Defender settings detect a virus and deletes the .exe:

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fWacatac.B!ml&threatid=2147735503

However, [VirusTotal shows only 3 vendors flagging it](https://www.virustotal.com/gui/file/d498f884e621550640948003e85fbfdf113eb195c4564acd62b54c1403ff8d03?nocache=1).

Probably not a lot you can do about it (I'm guessing it doesn't like scraping browser cookies?), but maybe add a note on the Readme so people aren't caught off guard?

**Comment by Q726kbXuN** [comment]
In as much as I can, I've verified that my build machine isn't the issue.  I used a non-windows machine to spin up an Windows cloud instance, and only installed the tools necessary, Python and Git both from trusted sources and vetting the downloads, after letting Windows install all updates it found to build the distribution.  The resulting package hit the same [alerts on VirusTotal](https://www.virustotal.com/gui/file/08557a7ace8e81262fcef28e62137a10672701ecf7c889bb85109cd287396910?nocache=1) as the one I previously built that you downloaded.

Of course, anyone reading this: Don't take my word for it, please feel free to recreate these steps or build on your machine to verify this.

That said, the standard response to these sort of false positives in Python packages, notably in PyInstaller, is to bring the latest version of packages and build the bootloader manually.  I've done both in the [0.72 pre-release](https://github.com/Q726kbXuN/nytxw_puz/releases/tag/0.72)

@hankscorpio83 Would you mind grabbing this version and see if it still triggers Windows Defender for you?  If this fixes it, I'll figure out how I want to check in my changes.  Otherwise, I'll probably just add a warning to the README as you suggest and move on.

**Comment by hankscorpio83** [comment]
Thanks for the quick response. Your tool got mentioned on [hackaday.com](https://hackaday.com/2021/09/24/nyt-crossword-decision-puzzles-many/), so I figured it'd be worth discussing.

The updated release triggers a different "virus" threat in Windows Defender and [two vendors flag it in VirusTotal](https://www.virustotal.com/gui/file/f32bd4e131653b600af88c5343719a6b0a41bc713a0e33a845676927827d8c6f).

**Comment by Q726kbXuN** [comment]
Thanks, I'll keep digging, but I've run out of time today.  I've added a note to the README.

For anyone else seeing this, I'd welcome any insights into which package or tool is triggering these so it can be removed.

**Comment by Q726kbXuN** [comment]
I've moved to [py2exe to build the executable](https://github.com/Q726kbXuN/nytxw_puz/releases/tag/0.73), and Virus Total seems happier, though still not perfectly happy.

I'm closing this for now, since Windows Defender should no longer trigger.  If it does for any reason, feel free to reopen this.
